// Generated by CoffeeScript 1.4.0
(function() {

  document.getElementById("color").focus();

  $(document).keydown(function(evt) {
    if (evt.keyCode === 13) {
      return $("body").css("background-color", $("#color").val());
    }
  });

}).call(this);
//@ sourceMappingURL=script.coffee.js.map