// Copyright 2015 The NW.js Authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// nw APP API
[implemented_in="content/nw/src/api/nw_app_api.h"]
namespace nw.App {
  enum ComponentExtensions {
    WIDEVINE
  };
  callback EventCallback = void();
  callback ErrorCallback = void(boolean result);
  callback ComponentCallback = void(DOMString version);
  interface Functions {
    // crash the renderer for testing
    [nocompile] static void crashRenderer();
    [nocompile] static void on(DOMString event, EventCallback callback);
    [nocompile] static void once(DOMString event,
                                 EventCallback callback);
    [nocompile] static void removeListener(DOMString event,
                                           EventCallback callback);
    [nocompile] static void removeAllListeners(DOMString event);
    static void enableComponent(ComponentExtensions extension_id, ComponentCallback callback);
    static void updateComponent(ComponentExtensions extension_id, ErrorCallback callback);
    static void quit();
    static void closeAllWindows();
    static void clearCache();
    static void clearAppCache(DOMString manifest_url);
    static void setProxyConfig(DOMString config, optional DOMString pac_url);
    [nocompile] static DOMString getProxyForURL(DOMString url);
    [nocompile] static void addOriginAccessWhitelistEntry(DOMString sourceOrigin, DOMString destinationProtocol, DOMString destinationHost, boolean allowDestinationSubdomains);
    [nocompile] static void removeOriginAccessWhitelistEntry(DOMString sourceOrigin, DOMString destinationProtocol, DOMString destinationHost, boolean allowDestinationSubdomains);
    static DOMString[] getArgvSync();
    static DOMString getDataPath();
    [nocompile] static DOMString getStartPath();
    static void crashBrowser();
  };
  interface Events {
    static void onOpen(DOMString cmdline);
    static void onReopen();
  };
};
