// nw APP API
[implemented_in="content/nw/src/api/nw_app_api.h"]
namespace nw.App {
  interface Functions {
    // crash the renderer for testing
    [nocompile] static void crashRenderer();
    static void quit();
    static void clearCache();
    static void setProxyConfig(DOMString config);
    [nocompile] static void addOriginAccessWhitelistEntry(DOMString sourceOrigin, DOMString destinationProtocol, DOMString destinationHost, boolean allowDestinationSubdomains);
    [nocompile] static void removeOriginAccessWhitelistEntry(DOMString sourceOrigin, DOMString destinationProtocol, DOMString destinationHost, boolean allowDestinationSubdomains);
    [nocompile] static DOMString[] argv();
    static DOMString[] getArgvSync();
  };
};
