// Copyright 2015 The NW.js Authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// nw APP API
[implemented_in="content/nw/src/api/nw_app_api.h"]
namespace nw.App {
  callback EventCallback = void();
  interface Functions {
    // crash the renderer for testing
    [nocompile] static void crashRenderer();
    [nocompile] static void on(DOMString event, EventCallback callback);
    [nocompile] static void once(DOMString event,
                                 EventCallback callback);
    [nocompile] static void removeListener(DOMString event,
                                           EventCallback callback);
    [nocompile] static void removeAllListeners(DOMString event);
    static void quit();
    static void closeAllWindows();
    static void clearCache();
    static void clearAppCache(DOMString manifest_url);
    static void setProxyConfig(DOMString config);
    [nocompile] static DOMString getProxyForURL(DOMString url);
    [nocompile] static void addOriginAccessWhitelistEntry(DOMString sourceOrigin, DOMString destinationProtocol, DOMString destinationHost, boolean allowDestinationSubdomains);
    [nocompile] static void removeOriginAccessWhitelistEntry(DOMString sourceOrigin, DOMString destinationProtocol, DOMString destinationHost, boolean allowDestinationSubdomains);
    static DOMString[] getArgvSync();
    static DOMString getDataPath();
    static void crashBrowser();
    static DOMString getDefaultAppUserModelID();
    static void setDefaultAppUserModelID(DOMString app_id);
  };
  interface Events {
    static void onOpen(DOMString cmdline);
    static void onReopen();
  };
};
