// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This is used by the NW window API internally to pass through messages to
// the shell window.
[implemented_in="content/nw/src/api/nw_window_api.h"]
namespace nw.currentWindowInternal {
  callback CapturePageCallback = void (DOMString dataUrl);
  callback ShowDevToolsCallback = void ();
  callback GetPrintersCallback = void (object[] printers);
  [noinline_doc] dictionary CapturePageOptions {
    [nodoc] DOMString? format;
    [nodoc] DOMString? datatype;
    [nodoc] long? quality;
  };

  dictionary MenuPatch {
    long menu;
    long index;
    object option;
  };

  interface Functions {
    static void close(optional boolean force);
    static void showDevToolsInternal(optional ShowDevToolsCallback callback);
    static void closeDevTools();
    static void setBadgeLabel(DOMString badge);
    static void requestAttentionInternal(long count);
    static void setProgressBar(double progress);
    static void enterKioskMode();
    static void leaveKioskMode();
    static void toggleKioskMode();
    static bool isKioskInternal();
    static void capturePageInternal(optional CapturePageOptions options, optional CapturePageCallback callback);
    static void clearMenu();
    static MenuPatch[] setMenu(long id);
    static void reloadIgnoringCache();
    static double getZoom();
    static void setZoom(double level);
    static void setShowInTaskbar(boolean show);
    static DOMString getTitleInternal();
    static void setTitleInternal(DOMString title);
    static object getWinParamInternal();
    static void getPrinters(GetPrintersCallback callback);
    static void setPrintSettingsInternal(optional object options);
    static DOMString getAppUserModelID();
    static void setAppUserModelID(DOMString id);
  };
};
