// Copyright 2015 The NW.js Authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// nw Object API
[implemented_in="content/nw/src/api/nw_object_api.h"]
namespace nw.Obj {
  interface Functions {
    static void create(long id, DOMString type, object options);
    static void destroy(long id);
    static void callObjectMethod(long id, DOMString type, DOMString method, any[] arguments);
    static any callObjectMethodSync(long id, DOMString type, DOMString method, any[] arguments);
    static void callObjectMethodAsync(long id, DOMString type, DOMString method, any[] arguments);
  };
};
