// nw Shell API
[implemented_in="content/nw/src/api/nw_shell_api.h"]
namespace nw.Shell {
  interface Functions {
    static void openExternal(DOMString uri);
    static void openItem(DOMString filePath);
    static void showItemInFolder(DOMString filePath);
  };
};
